---
version: '2'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: task_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task

